'use strict';
const STORAGE_KEY='hana-todo-v1';
const $=selector=>document.querySelector(selector);
const priorityLabels={high:'높음',normal:'보통',low:'낮음'};
const priorityRanks={high:0,normal:1,low:2};
const todayKey=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};
function validDate(value){if(value==='')return true;if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||value<'0001-01-01')return false;const parsed=new Date(value+'T12:00:00Z');return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===value;}
function validateTasks(value){if(!Array.isArray(value)||value.length>10000)throw new Error('invalid');const ids=new Set();return value.map(item=>{if(!item||typeof item.id!=='string'||!item.id||item.id.length>100||ids.has(item.id)||typeof item.title!=='string'||!item.title.trim()||item.title.length>300||!Object.hasOwn(priorityRanks,item.priority)||!validDate(item.due)||typeof item.done!=='boolean'||!Number.isFinite(item.createdAt)||!Number.isFinite(item.updatedAt))throw new Error('invalid');ids.add(item.id);return {id:item.id,title:item.title.trim(),due:item.due,priority:item.priority,done:item.done,createdAt:item.createdAt,updatedAt:item.updatedAt};});}
let tasks=[],filter='all',editId=null,undoAction=null,toastTimer=null,installPrompt=null,storageBroken=false;
try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)tasks=validateTasks(JSON.parse(saved));}catch(error){storageBroken=true;}
function notify(message,action=null){clearTimeout(toastTimer);$('#toast-message').textContent=message;$('#toast').hidden=false;$('#undo').hidden=!action;undoAction=action;toastTimer=setTimeout(()=>{$('#toast').hidden=true;undoAction=null;},7000);}
function commit(next){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));storageBroken=false;tasks=next;render();return true;}catch(error){notify('저장할 수 없어 변경하지 않았어요. 브라우저 저장 공간을 확인해주세요.');return false;}}
function compareTasks(a,b){if(a.done!==b.done)return Number(a.done)-Number(b.done);if(a.done)return b.updatedAt-a.updatedAt;return (a.due||'9999-99-99').localeCompare(b.due||'9999-99-99')||priorityRanks[a.priority]-priorityRanks[b.priority]||a.createdAt-b.createdAt;}
function dueText(due){if(!due)return '기한 없음';const now=todayKey();if(due===now)return '오늘';const delta=Math.round((new Date(due+'T12:00:00Z')-new Date(now+'T12:00:00Z'))/86400000);if(delta<0)return `${Math.abs(delta)}일 지남`;if(delta===1)return '내일';return `${Number(due.slice(5,7))}월 ${Number(due.slice(8,10))}일${due.slice(0,4)!==now.slice(0,4)?' · '+due.slice(0,4):''}`;}
function element(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function makeRow(task){const today=todayKey();const status=!task.done&&task.due?(task.due<today?'overdue':task.due===today?'today':''):'';const row=element('article',`task-row ${status} ${task.done?'done':''}`);row.dataset.id=task.id;const check=element('input','check');check.type='checkbox';check.checked=task.done;check.setAttribute('aria-label',`${task.title} ${task.done?'완료 취소':'완료'}`);check.addEventListener('change',()=>{const now=Date.now();if(!commit(tasks.map(item=>item.id===task.id?{...item,done:check.checked,updatedAt:now}:item)))check.checked=task.done;});const body=element('div','task-body');body.append(element('div','task-title',task.title));const meta=element('div','task-meta');const due=element('span',status==='overdue'?'due-overdue':status==='today'?'due-today':'',dueText(task.due));if(task.due)due.title=task.due;if(task.due)meta.append(due);if(task.priority!=='normal')meta.append(element('span',`priority ${task.priority}`,priorityLabels[task.priority]));if(meta.childNodes.length)body.append(meta);const actions=element('div','task-actions');const edit=element('button','icon-button edit-button','✎');edit.setAttribute('aria-label',`${task.title} 수정`);edit.title='수정';edit.addEventListener('click',()=>{editId=task.id;$('#edit-title').value=task.title;$('#edit-due').value=task.due;$('#edit-priority').value=task.priority;$('#edit-dialog').showModal();});const remove=element('button','icon-button','×');remove.setAttribute('aria-label',`${task.title} 삭제`);remove.title='삭제';remove.addEventListener('click',()=>{if(commit(tasks.filter(item=>item.id!==task.id)))notify('할 일을 삭제했어요.',()=>{if(!tasks.some(item=>item.id===task.id))commit([...tasks,task]);});});actions.append(edit,remove);row.append(check,body,actions);return row;}
function render(){const today=todayKey(),remaining=tasks.filter(task=>!task.done);$('#count-all').textContent=remaining.length;$('#count-today').textContent=remaining.filter(task=>task.due&&task.due<=today).length;const visible=tasks.filter(task=>filter==='today'?task.due&&task.due<=today:true).sort(compareTasks);const list=$('#task-list');list.replaceChildren(...visible.map(makeRow));$('#empty').hidden=visible.length>0;document.querySelectorAll('[data-filter]').forEach(button=>{button.classList.toggle('active',button.dataset.filter===filter);button.setAttribute('aria-pressed',String(button.dataset.filter===filter));});}
$('#add-form').addEventListener('submit',event=>{event.preventDefault();const title=$('#task-title').value.trim(),due=$('#task-due').value;if(!title){$('#task-title').focus();return;}if(!validDate(due)){notify('올바른 마감일을 선택해주세요.');return;}if(tasks.length>=10000){notify('목록이 가득 찼어요. 백업 후 완료한 일을 정리해주세요.');return;}const now=Date.now();if(commit([...tasks,{id:crypto.randomUUID(),title,due,priority:$('#task-priority').value,done:false,createdAt:now,updatedAt:now}])){$('#task-title').value='';$('#task-due').value='';$('#task-priority').value='normal';if(filter!=='all'){filter='all';render();}$('#task-title').focus();}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;render();}));
document.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
$('#edit-form').addEventListener('submit',event=>{event.preventDefault();const title=$('#edit-title').value.trim(),due=$('#edit-due').value;if(!title||!validDate(due)){notify('할 일과 마감일을 확인해주세요.');return;}if(commit(tasks.map(task=>task.id===editId?{...task,title,due,priority:$('#edit-priority').value,updatedAt:Date.now()}:task)))$('#edit-dialog').close();});
$('#backup-open').addEventListener('click',()=>$('#backup-dialog').showModal());
$('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({app:'hana-todo',version:1,exportedAt:new Date().toISOString(),tasks},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=element('a');link.href=url;link.download=`하나씩-백업-${todayKey()}.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('백업 파일을 저장했어요.');});
$('#import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw new Error('size');const backup=JSON.parse(await file.text());if(backup.app!=='hana-todo'||backup.version!==1)throw new Error('format');const incoming=validateTasks(backup.tasks),ids=new Set(tasks.map(task=>task.id)),newTasks=incoming.filter(task=>!ids.has(task.id));if(tasks.length+newTasks.length>10000)throw new Error('size');if(commit([...tasks,...newTasks])){notify(`${newTasks.length}개의 할 일을 불러왔어요.`);$('#backup-dialog').close();}}catch(error){notify('올바른 하나씩 백업 파일을 선택해주세요. 현재 목록은 유지돼요.');}finally{event.target.value='';}});
$('#undo').addEventListener('click',()=>{const action=undoAction;undoAction=null;$('#toast').hidden=true;if(action)action();});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;}else $('#install-dialog').showModal();});
window.addEventListener('storage',event=>{if(event.key!==STORAGE_KEY)return;try{tasks=event.newValue?validateTasks(JSON.parse(event.newValue)):[];render();}catch(error){notify('다른 창의 저장 내용을 읽을 수 없어요. 백업을 확인해주세요.');}});
window.addEventListener('focus',render);setInterval(render,60000);
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();if(storageBroken){notify('저장 내용을 읽을 수 없어요. 백업 파일이 있다면 불러와주세요.');}
